import type { Hero, SkillElement } from "./engine/types";

export const ELEMENT_COLORS: Record<SkillElement, string> = {
  physical: "#e4e4e7",
  fire: "#f97316",
  ice: "#38bdf8",
  earth: "#c2851b",
  storm: "#a78bfa",
  holy: "#fde047",
  shadow: "#8b5cf6",
};

export const ELEMENT_LABELS: Record<SkillElement, string> = {
  physical: "Physical",
  fire: "Fire",
  ice: "Ice",
  earth: "Earth",
  storm: "Storm",
  holy: "Holy",
  shadow: "Shadow",
};

export const HEROES: Hero[] = [
  {
    id: "alden",
    name: "Ser Alden",
    archetype: "Vanguard",
    blurb:
      "An immovable shield-bearer who grinds foes down and shrugs off the killing blow.",
    color: "#3b82f6",
    accent: "#1d4ed8",
    maxHp: 145,
    maxMp: 40,
    atk: 22,
    def: 13,
    spd: 6,
    critChance: 0.08,
    critMult: 1.5,
    passive: {
      id: "bulwark",
      name: "Bulwark",
      description: "Takes 30% less damage while below 30% HP.",
    },
    skill: {
      id: "skill",
      name: "Shield Bash",
      description: "Heavy blow that stuns the target for 1 round.",
      element: "earth",
      mpCost: 12,
      cooldown: 2,
      mode: "damage",
      mult: 1.35,
      applies: { kind: "stun", duration: 1, power: 1 },
    },
    ultimate: {
      id: "ultimate",
      name: "Glacial Bastion",
      description: "Shattering slam that weakens the target for 2 rounds.",
      element: "ice",
      mpCost: 30,
      cooldown: 3,
      mode: "damage",
      mult: 2.2,
      applies: { kind: "weaken", duration: 2, power: 0.3 },
    },
  },
  {
    id: "kargath",
    name: "Kargath",
    archetype: "Berserker",
    blurb:
      "A reckless brawler who hits hardest when he is closest to death.",
    color: "#ef4444",
    accent: "#991b1b",
    maxHp: 125,
    maxMp: 30,
    atk: 30,
    def: 6,
    spd: 8,
    critChance: 0.14,
    critMult: 1.6,
    passive: {
      id: "berserk",
      name: "Berserk",
      description: "Gains 30% ATK while below 40% HP.",
    },
    skill: {
      id: "skill",
      name: "Reckless Cleave",
      description: "Burning slash that leaves the target alight for 2 rounds.",
      element: "fire",
      mpCost: 10,
      cooldown: 2,
      mode: "damage",
      mult: 1.65,
      applies: { kind: "burn", duration: 2, power: 8 },
    },
    ultimate: {
      id: "ultimate",
      name: "Blood Fury",
      description: "A devastating flurry with no riders attached.",
      element: "physical",
      mpCost: 28,
      cooldown: 3,
      mode: "damage",
      mult: 2.7,
    },
  },
  {
    id: "vex",
    name: "Vex",
    archetype: "Assassin",
    blurb:
      "Strikes first and strikes for the throat, but folds under sustained pressure.",
    color: "#a855f7",
    accent: "#6b21a8",
    maxHp: 100,
    maxMp: 35,
    atk: 32,
    def: 4,
    spd: 14,
    critChance: 0.3,
    critMult: 2.0,
    passive: {
      id: "lethality",
      name: "Lethality",
      description: "+15% critical strike chance.",
    },
    skill: {
      id: "skill",
      name: "Shadow Strike",
      description: "Umbral stab that weakens the target for 2 rounds.",
      element: "shadow",
      mpCost: 12,
      cooldown: 2,
      mode: "damage",
      mult: 1.5,
      applies: { kind: "weaken", duration: 2, power: 0.25 },
    },
    ultimate: {
      id: "ultimate",
      name: "Death Mark",
      description: "A single perfect strike with enormous critical potential.",
      element: "shadow",
      mpCost: 30,
      cooldown: 4,
      mode: "damage",
      mult: 3.0,
    },
  },
  {
    id: "lyra",
    name: "Lyra",
    archetype: "Mage",
    blurb:
      "A glass cannon who trades durability for the biggest raw damage in the arena.",
    color: "#f97316",
    accent: "#c2410c",
    maxHp: 95,
    maxMp: 60,
    atk: 28,
    def: 5,
    spd: 9,
    critChance: 0.12,
    critMult: 1.6,
    passive: {
      id: "mana-surge",
      name: "Mana Surge",
      description: "Skill and ultimate MP costs are reduced by 30%.",
    },
    skill: {
      id: "skill",
      name: "Ember Lance",
      description: "A spear of flame that burns for 3 rounds.",
      element: "fire",
      mpCost: 14,
      cooldown: 2,
      mode: "damage",
      mult: 1.5,
      applies: { kind: "burn", duration: 3, power: 7 },
    },
    ultimate: {
      id: "ultimate",
      name: "Meteor",
      description: "Calls down a meteor, leaving the target burning for 3 rounds.",
      element: "fire",
      mpCost: 34,
      cooldown: 3,
      mode: "damage",
      mult: 2.8,
      applies: { kind: "burn", duration: 3, power: 10 },
    },
  },
  {
    id: "mira",
    name: "Mira",
    archetype: "Support",
    blurb:
      "The only hero who can heal herself, outlasting opponents through attrition.",
    color: "#10b981",
    accent: "#047857",
    maxHp: 110,
    maxMp: 55,
    atk: 18,
    def: 8,
    spd: 7,
    critChance: 0.1,
    critMult: 1.5,
    passive: {
      id: "renewal",
      name: "Renewal",
      description: "Regenerates 5% of max HP at the start of each round.",
    },
    skill: {
      id: "skill",
      name: "Mend",
      description: "Restores 30% of max HP.",
      element: "holy",
      mpCost: 14,
      cooldown: 2,
      mode: "heal",
      mult: 0.3,
    },
    ultimate: {
      id: "ultimate",
      name: "Sanctuary",
      description: "Restores 55% of max HP and clears all status effects.",
      element: "holy",
      mpCost: 32,
      cooldown: 4,
      mode: "heal",
      mult: 0.55,
      cleanses: true,
    },
  },
  {
    id: "fen",
    name: "Fen",
    archetype: "Ranger",
    blurb:
      "A precise skirmisher whose critical shots punch straight through armor.",
    color: "#22d3ee",
    accent: "#0e7490",
    maxHp: 105,
    maxMp: 45,
    atk: 27,
    def: 7,
    spd: 12,
    critChance: 0.22,
    critMult: 1.8,
    passive: {
      id: "precision",
      name: "Precision",
      description: "Critical hits ignore the target's DEF.",
    },
    skill: {
      id: "skill",
      name: "Piercing Shot",
      description: "An armor-piercing shot that weakens for 2 rounds.",
      element: "physical",
      mpCost: 12,
      cooldown: 2,
      mode: "damage",
      mult: 1.55,
      applies: { kind: "weaken", duration: 2, power: 0.25 },
    },
    ultimate: {
      id: "ultimate",
      name: "Rain of Arrows",
      description: "A storming volley that burns the target for 2 rounds.",
      element: "storm",
      mpCost: 30,
      cooldown: 3,
      mode: "damage",
      mult: 2.4,
      applies: { kind: "burn", duration: 2, power: 9 },
    },
  },
];

export function getHero(id: string): Hero | undefined {
  return HEROES.find((hero) => hero.id === id);
}

export const DEFAULT_P1_HERO_ID = HEROES[0].id;
export const DEFAULT_P2_HERO_ID = HEROES[2].id;
